[tool.poetry]
name = "cfggme"
version = "0.1.0"
description = "Curvature Filtrations for Graph Generative Models"
authors = ["jeremy.wayland <jeremy.don.wayland@gmail.com>"]
license = "BSD 3-Clause License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.26.1"
networkx = "^3.2"
POT = "^0.9.1"
gudhi = "^3.8.0"
joblib = "^1.3.2"
pandas = "^2.1.1"
scipy = "^1.11.3"
python_log_indenter = "^0.9"
scikit-learn = "^1.3.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
