name: Build and Deploy Documentation

# Run workflow on push to main branch and when manually triggered.
on:
  push:
    branches:
      - main # Trigger workflow on new commits to the main branch
    tags:
      - "*" # Optional: also trigger on new tags
  workflow_dispatch: # Allow manual runs from GitHub UI

# Restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Use the correct version of checkout

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"
          cache: "pip"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Build Sphinx documentation
        run: |
          poetry run sphinx-build -b html docs/source docs/build/html

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html # Upload the built documentation as an artifact

  # Deploy the artifact to GitHub Pages.
  deploy:
    needs: build # Deploy only after the 'build' job succeeds
    runs-on: ubuntu-latest
    permissions:
      pages: write # Grant permission to write to GitHub Pages
      id-token: write # Required to authenticate with GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: docs/build/html # Path where the Sphinx docs are stored
